### PR TITLE
Add new tools

### PR DESCRIPTION
**Pull request by a-solovyev12**
Add `scmap-preprocess` as an individual tool.

### CODE REVIEW

**Review by pcm32 — APPROVED** [review]
LGTM

**Comment by pcm32** [comment]
You might want to wait until the deploy job runs at the other side...

**Comment by pcm32** [comment]
(so that your revisions on the toolshed get pulled here on the lock files by the CI)

**Comment by a-solovyev12** [comment]
okay, I'll merge it after the CI finishes

**Pull request merged**
